### ISSUE TITLE
Change in image name for selenium-node-chrome-debug

### ISSUE THREAD

**Issue by ashwinsgm** [ddavison/selenium-openshift-templates#14]
Can you please confirm if it is image: selenium-node-chrome-debug or image: selenium/node-chrome-debug in selenium-node-chrome-debug.yaml in Line number 77

**Comment by ddavison** [comment]
that's correct @ashwinsgm .  cc @jemacom .

`image` should be `selenium/node-chrome-debug``

**Comment by ddavison** [comment]
though i think @jemacom was actually using the local Docker images that you can build in the root directory.  it really can be anything, but you're right. it should at least default to `selenium/node-chrome-debug`

**Comment by ddavison** [comment]
fixed in bee1691fee4405e95e89957fb7e8eeaea9a2f3b3 and c5b755acf3531f2af46ac91ae7bf5dbba81f90ac
