### ISSUE TITLE
selenium-openshift-templates for nodes are missing

### ISSUE THREAD

**Issue by sgraza** [ddavison/selenium-openshift-templates#16]
Hello,

I just noticed that you deleted folders for the selenium nodes. When I run the Openshift, the build was failed because it can't find the folders.

This line is part of the template:

      git:   
        uri: https://github.com/ddavison/selenium-openshift-templates   
        ref: master   

Please help. Thanks!

**Comment by ddavison** [comment]
whoops! apologies. reverted in 786d1bde218f1947b43f6cedf1d75306655f6231
