### ISSUE TITLE
Cannot remote to selenium grid in the server

### ISSUE THREAD

**Issue by Jescs** [ddavison/selenium-openshift-templates#25]
Hello all,

I cant remote my request.  I create the selenium-grid in Cloud opensift, but got error.
driver = webdriver.Remote("http://{pod ip add}/wd/hub", desired_capabilities=chrome_capabilities)
error msg :
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='XXX', port=5555): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002096F5D7430>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))

Cloud you please help me.

**Comment by ddavison** [comment]
It looks like this would be a networking issue not necessarily related to these specific templates.

I hope you were able to get this networking issue resolved! Closing.
